/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

//Import Ecosystem
import Business.EcoSystem;

//Import Employee
import Business.Employee.Employee;


//Import Organization
import Business.Organization;

//Import User Account 
import Business.UserAccount.UserAccount;


//Import Delivery Man Role
import Business.Role.DeliveryManRole;


//Import CardLayout
import java.awt.CardLayout;

//Import Color
import java.awt.Color;

//Import Component
import java.awt.Component;

//Import RegEx
import java.util.regex.Matcher;
import java.util.regex.Pattern;

//import BorderFactory
import javax.swing.BorderFactory;

//import JOptionPane
import javax.swing.JOptionPane;

//import JPanel
import javax.swing.JPanel;

/**
 *
 * @author merwinroy
 */
public class AddDeliveryAgentJPanel extends javax.swing.JPanel 
{

    /**
     * Creates new form CreateNewManagerJPanel
     */
    //Import JPanel sequenceJPanel object
    JPanel sequenceJPanel;
    
    //Import Organization object
    Organization organization;
    
    //Import Ecosystem object
    EcoSystem ecoSystem;
    
    
  
    
    public AddDeliveryAgentJPanel(JPanel sequenceJPanel,EcoSystem ecoSystem,Organization organization) 
    {
        //Initialize components
        initComponents();
        
        this.sequenceJPanel = sequenceJPanel;
        
        this.ecoSystem=ecoSystem;
        
        this.organization=organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblOrgtype = new javax.swing.JLabel();
        txtAgentName = new javax.swing.JTextField();
        txtOrgType = new javax.swing.JTextField();
        btnCreateDeliveryAgent = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        lblDeliveryAgent = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblOrgName = new javax.swing.JLabel();
        txtOrgName = new javax.swing.JTextField();
        lblSignUp = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText(" NEW DELIVERY AGENT PANEL");
        lblTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 3));

        lblOrgtype.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOrgtype.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrgtype.setText("Organization Type:");

        txtOrgType.setEnabled(false);
        txtOrgType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrgTypeActionPerformed(evt);
            }
        });

        btnCreateDeliveryAgent.setBackground(new java.awt.Color(255, 255, 255));
        btnCreateDeliveryAgent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCreateDeliveryAgent.setText("Create ");
        btnCreateDeliveryAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDeliveryAgentActionPerformed(evt);
            }
        });

        btnBack.setText(" Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblDeliveryAgent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDeliveryAgent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeliveryAgent.setText("Delivery Agent Name:");

        lblUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserName.setText("User Name:");

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword.setText("Password:");

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        lblOrgName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOrgName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrgName.setText("Organization Name:");

        txtOrgName.setEnabled(false);
        txtOrgName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrgNameActionPerformed(evt);
            }
        });

        lblSignUp.setText("Sign-Up");
        lblSignUp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreateDeliveryAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(lblSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDeliveryAgent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrgtype, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrgName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOrgName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAgentName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(114, 399, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOrgType, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrgName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOrgName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrgtype, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOrgType, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeliveryAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAgentName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(lblSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateDeliveryAgent))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateDeliveryAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDeliveryAgentActionPerformed
        // TODO add your handling code here:
        
        //For loop to iterate through list of user accounts
        for(UserAccount account : organization.getUserAccountDirectory().getUserAccountList())
        {
            //Check for already existing username
            if(account.getUsername().equals(txtUserName.getText()))
            {
                 //Show MessageDialog
                JOptionPane.showMessageDialog(null, "Username is already in use");
                
                return;
            }
        }
        
        //Check for password pattern
        if (passwordPatternCheck()==false)
        {
            
            
            //Show message dialog
            JOptionPane.showMessageDialog(null, "Password should be at least 6 digits and contain at least one upper case letter, one lower case letter, one digit and one special character $, *, # or &.");
            
            return;
        }
        else
        {
            
            lblPassword.setForeground (Color.BLACK);
            
            txtPassword.setBorder(BorderFactory.createLineBorder(Color.black));
            
        }
        
        //Check for username pattern
        if (usernamePatternCheck()==false)
        {
            
            //Show MessageDialog
            JOptionPane.showMessageDialog(null, "Username should be in the format of xx_xx@xx.xx");
            
            return;
        } 
        else
        {
            lblUserName.setForeground (Color.BLACK);
            
            txtUserName.setBorder(BorderFactory.createLineBorder(Color.black));
            
        }
        
      
        //Retrieving texts from textfields and storing in String objects
        String userName=txtUserName.getText();
        
        String password=txtPassword.getText();
        
        String employeeName=txtAgentName.getText();
      
     
     //Employee object created
     Employee employee=organization.
             getEmployeeDirectory().
             createEmployee(employeeName);
     
     organization.
             getUserAccountDirectory().
             createUserAccount(userName,password,employee,new DeliveryManRole());
     
     //Show message dialog
     JOptionPane.showMessageDialog(null, "Delivery agent has been added into the system successfully");
    }//GEN-LAST:event_btnCreateDeliveryAgentActionPerformed
    
    //Function for password pattern check
    private boolean passwordPatternCheck()
    {
        
        //Pattern variable that fetches pattern to follow
        Pattern pattern = Pattern.compile("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,}$");
        
        //matcher variable matches pattern with text
        Matcher matcher = pattern.matcher(txtPassword.getText());
        
        //boolean variable fetches result
        boolean bool = matcher.matches();
        
        return bool;
    }
    
    //Function for username pattern check
    private boolean usernamePatternCheck()
    {
        //Pattern variable that fetches pattern to follow
        Pattern pattern=Pattern.compile("^[a-zA-Z0-9]+_[a-zA-Z0-9]+@[a-zA-Z0-9]+.[a-zA-Z0-9]+$");
        
        //matcher variable matches pattern with text
        Matcher matcher=pattern.matcher(txtUserName.getText());
        
        //boolean variable fetches result
        boolean bool=matcher.matches();
        
        return bool;
    }
    
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        //CardLayout object created
        CardLayout cardLayout = (CardLayout)sequenceJPanel.getLayout();
        
        //current layout removed from panel
        sequenceJPanel.remove(this);
        
        //previous layout is loaded
        cardLayout.previous(sequenceJPanel);
        
        //component array is created where components from panel are fetched and stored
        Component[] components = this.sequenceJPanel.
                getComponents();
        
        //for loop to iterate through all components
        for(Component component : components)
        {
            if(component instanceof DeliveryAgentManagementJPanel)
            {
                 //DeliveryManagementJpanel object is created
                DeliveryAgentManagementJPanel damPanel= (DeliveryAgentManagementJPanel) component;
                
                damPanel.populateTbl(); 
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtOrgNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrgNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrgNameActionPerformed

    private void txtOrgTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrgTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrgTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateDeliveryAgent;
    private javax.swing.JLabel lblDeliveryAgent;
    private javax.swing.JLabel lblOrgName;
    private javax.swing.JLabel lblOrgtype;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSignUp;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtAgentName;
    private javax.swing.JTextField txtOrgName;
    private javax.swing.JTextField txtOrgType;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
