/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

//Import Ecosystem
import Business.EcoSystem;


//Import organization
import Business.Organization;

//Import useraccount
import Business.UserAccount.UserAccount;

//import cardLayout
import java.awt.CardLayout;

//import component
import java.awt.Component;

//import JOptionPane
import javax.swing.JOptionPane;

//Import JPanel
import javax.swing.JPanel;

//Import tableModel
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author merwinroy
 */
public class CustomerManagementJPanel extends javax.swing.JPanel 
{
    //JPanel container object
    JPanel container;
    
    //Ecosystem object
    EcoSystem ecoSystem;
    
    //Organization object
    Organization organization;
    
    
    public CustomerManagementJPanel(JPanel container,EcoSystem ecoSystem,Organization organization) 
    {
        //Initialize components
        initComponents();
        
        this.container=container;
        
        this.ecoSystem=ecoSystem;
        
        this.organization=organization;
        
        populateTable();
    }
    public void populateTable()
    {
        //table model object is created
        DefaultTableModel tableModel = (DefaultTableModel) tblCustomerManagement.getModel();
        
        //row count for model is set to 0
        tableModel.setRowCount(0);
        
        //organization object is created
        Organization organizationCopy=ecoSystem.
                getCustomerDirectory().
                findOrganization("Customer");
        
        //for loop to iterate through list of user accounts
        for(UserAccount account:organizationCopy.getUserAccountDirectory().getUserAccountList()) 
        {
            Object row[] = new Object[3];
            
            row[0] = account.getEmployee().getName();
            
            row[1] = account;
      
            //add row to table model after every iteration
            tableModel.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomerManagement = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblOptions = new javax.swing.JLabel();
        lblUpdate = new javax.swing.JLabel();
        lblDelete = new javax.swing.JLabel();
        lblCreate = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        tblCustomerManagement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "UserName"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCustomerManagement);

        lblTitle.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("CUSTOMER MANAGEMENT PANEL");
        lblTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 3));

        btnCreate.setBackground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnBack.setText(" Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblOptions.setText("Options");
        lblOptions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 2));

        lblUpdate.setText("<- To update existing customer records");

        lblDelete.setText("<- To delete customer records");

        lblCreate.setText("<- To add a new customer into the system");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnCreate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        
        //AddCustomerJPanel object is created
        AddCustomerJPanel addCustomerPanel = new AddCustomerJPanel(container,ecoSystem,organization);
        
        //panel object is added to container
        container.add("AddCustomerJPanel", addCustomerPanel);
        
        //cardLayout object is created
        CardLayout cardLayout = (CardLayout) container.getLayout();
        
        //next container layout is set
        cardLayout.next(container);

    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        //Selected row in table
        int selectedRow = tblCustomerManagement.getSelectedRow();
        
        //prompts error if no row is selected
        if (selectedRow < 0) 
        {
            //Show message Dialog
            JOptionPane.showMessageDialog(null, "Please select a row from table to proceed");
            
            return;
        }
        else
        {
            //Useraccount object is created
            UserAccount account = (UserAccount)tblCustomerManagement.getValueAt(selectedRow, 1);
            
            //UpdateCustomerJPanel object is created
            UpdateCustomerJPanel updatePanel = new UpdateCustomerJPanel(container,account,"Customers");
            
            //panel object added to container
            container.add("UpdateCustomerJPanel", updatePanel);
            
            //cardlayout is created
            CardLayout cardLayout = (CardLayout) container.getLayout();
            cardLayout.next(container);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        //selected row from table
        int selectedRow = tblCustomerManagement.getSelectedRow();
        
        //prompts error if no row is selected
        if (selectedRow < 0) 
        {
            //show messageDialog
            JOptionPane.showMessageDialog(null, "Please select a row from table to proceed!");
            
            return;
        }
        else
        {
            //Useraccount object selected from table
            UserAccount user = (UserAccount)tblCustomerManagement.getValueAt(selectedRow, 1);
            
            //delete account
            organization.
                    getUserAccountDirectory().
                    deleteAccount(user);
            
            //delete employee details from directory
            organization.
                    getEmployeeDirectory().
                    deleteEmployee(user.getEmployee());
            
            //show message dialog
            JOptionPane.showMessageDialog(null, "User Account has been deleted successfully");
        } 
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        //removing current container
        container.remove(this);
        
        //cardLayout is created
        CardLayout cardLayout = (CardLayout) container.getLayout();
        
        //previous layout is loaded
        cardLayout.previous(container);
        
        //Components array created to fetch and store components from panel
        Component[] components = this.container.
                getComponents();
        
        //for loop to iterate through components
        for(Component component : components)
        {
            
            if(component instanceof SystemAdminWorkAreaJPanel)
            {
                //systemAdminWorkArea panel object created
                SystemAdminWorkAreaJPanel sawaPanel= (SystemAdminWorkAreaJPanel) component;
                
                sawaPanel.populateTree(); 
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblDelete;
    private javax.swing.JLabel lblOptions;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JTable tblCustomerManagement;
    // End of variables declaration//GEN-END:variables
}
