/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

//Import Ecosystem
import Business.EcoSystem;

//Import Organization
import Business.Organization;

//Import UserAccount
import Business.UserAccount.UserAccount;

//Import CardLayout
import java.awt.CardLayout;

//Import Component
import java.awt.Component;

//Import JOptionPane
import javax.swing.JOptionPane;

//Import JPanel
import javax.swing.JPanel;

//Import table Model
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author merwinroy
 */
public class DeliveryAgentManagementJPanel extends javax.swing.JPanel 
{

    /**
     * Creates new form RestaurantManagementJPanel
     */
    
    //JPanel container object
    JPanel container;
    
    //Ecosystem object
    EcoSystem ecoSystem;
    
    //Organization object
    Organization organization;
    
    
    public DeliveryAgentManagementJPanel(JPanel container,EcoSystem ecoSystem,Organization organization) 
    {
        //Initialize components
        initComponents();
        
        this.container= container;
        
        this.ecoSystem=ecoSystem;
        
        this.organization=organization;
        
        populateTbl();
        
    }
    public void populateTbl()
    {
        //Table Model object created
        DefaultTableModel tableModel = (DefaultTableModel) tblDeliveryAgentManagement.getModel();
        
        //row count set to 0
        tableModel.setRowCount(0);
        
        //search delivery agent in organization
        Organization org=ecoSystem.getDeliveryManDirectory().
                findOrganization("DeliveryMan") ;
        
        //for loopt to iterate through user account list
        for(UserAccount user:org.getUserAccountDirectory().getUserAccountList()) 
        {
            Object row[] = new Object[3];
            
            row[0] = user.
                    getEmployee().
                    getName();
            
            row[1] = user;
           
            //add row to model after every iteration
            tableModel.addRow(row);
        
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.deliv
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDeliveryAgentManagement = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblOptions = new javax.swing.JLabel();
        lblUpdate = new javax.swing.JLabel();
        lblDelete = new javax.swing.JLabel();
        lblCreate = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        tblDeliveryAgentManagement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "UserName"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDeliveryAgentManagement);

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("DELIVERY AGENT MANAGEMENT PANEL");
        lblTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 3));

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update ");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete ");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnBack.setText(" Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblOptions.setText("Options");
        lblOptions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 2));

        lblUpdate.setText("<- To update existing delivery agent records");

        lblDelete.setText("<- To delete delivery agent records");

        lblCreate.setText("<- To add a new delivery agent into the system");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCreate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)))
                .addContainerGap(93, Short.MAX_VALUE))
            .addComponent(lblOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblTitle)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(lblOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpdate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDelete))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreate))
                .addGap(10, 10, 10)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        
        //AddDeliveryAgentJPanel object is created
        AddDeliveryAgentJPanel addDeliveryAgentpanel = new AddDeliveryAgentJPanel(container,ecoSystem,organization);
        
        //panel object added to container
        container.add("AddDeliveryAgentJPanel", addDeliveryAgentpanel);
        
        //Cardlayout object is created
        CardLayout layout = (CardLayout) container.getLayout();
        
        //next layout is loaded
        layout.next(container);

    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        //Selected Row
        int selectedRow = tblDeliveryAgentManagement.getSelectedRow();
        
        //Prompts error if no row is selected
        if (selectedRow < 0) 
        {
            //show error message
            JOptionPane.showMessageDialog(null, "Please select a row from table to proceed");
            
            return;
        }
        else
        {
            //UserAccount object is selected from table row
            UserAccount user = (UserAccount)tblDeliveryAgentManagement.getValueAt(selectedRow, 1);
            
            //UpdateManagerJPanel object is created
            UpdateManagerJPanel updateManagerPanel = new UpdateManagerJPanel(container,user,"DeliveryMan");
            
            //panel object added to container
            container.add("UpdateManagerJPanel", updateManagerPanel);
            
            //cardlayout object is created
            CardLayout cardLayout = (CardLayout) container.getLayout();
            
            //next layout is loaded
            cardLayout.next(container);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        //Row is selected from table
        int selectedRow = tblDeliveryAgentManagement.getSelectedRow();
        
        //prompts error if no row is selected
        if (selectedRow < 0) 
        {
            //show MessageDialog
            JOptionPane.showMessageDialog(null, "Please select a row from table to proceed");
            
            return;
        }
        else
        {
            //UserAccount object is selected from table
            UserAccount account = (UserAccount)tblDeliveryAgentManagement.getValueAt(selectedRow, 1);
            
            
            //delete employee details from organization
            organization.getEmployeeDirectory().deleteEmployee(account.getEmployee());
            
            //delete account from organization
            organization.getUserAccountDirectory().deleteAccount(account);
          
            
            //Show message dialog
            JOptionPane.showMessageDialog(null, "User Account has been deleted successfully");
    } 
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        //Current container layout is removed
        container.remove(this);
        
        //Cardlayout object is created
        CardLayout cardLayout = (CardLayout) container.getLayout();
        
        //previous layout is loaded
        cardLayout.previous(container);
        
        //Components array is created to fetch and store components from container
        Component[] components = this.container.getComponents();
        
        //for loop to iterate through components
        for(Component component : components)
        {
            
            if(component instanceof SystemAdminWorkAreaJPanel)
            {
                //SystemAdminWorkAreaJPanel object created
                SystemAdminWorkAreaJPanel sawaPanel= (SystemAdminWorkAreaJPanel) component;
                
                sawaPanel.populateTree(); 
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblDelete;
    private javax.swing.JLabel lblOptions;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JTable tblDeliveryAgentManagement;
    // End of variables declaration//GEN-END:variables
}
