/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

//Import Ecosystem
import Business.EcoSystem;

//Import Useraccount
import Business.UserAccount.UserAccount;

//Import cardLayout
import java.awt.CardLayout;

//Import color
import java.awt.Color;

//import regex
import java.util.regex.Matcher;
import java.util.regex.Pattern;

//import borderfactory
import javax.swing.BorderFactory;

//import JOptionPane
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author merwinroy
 */
public class UpdateManagerJPanel extends javax.swing.JPanel {

    //JPanel sequenceJPanel object
    JPanel sequenceJPanel;
    
    //UserAccount object
    UserAccount userAccount;
    
    //organizatioName object
    String organizationName;
    
    //ecosystem object
    EcoSystem ecosystem;
    
    //CustomerManagementJPanel object
    CustomerManagementJPanel customerManagementPanel;
    
    
    UpdateManagerJPanel(JPanel sequenceJPanel,UserAccount userAccount,String organaizationName) 
    {
        //initialize components
        initComponents();
        
        this.sequenceJPanel = sequenceJPanel;
        this.userAccount=userAccount;
        this.organizationName=organaizationName;
        this.ecosystem=ecosystem;
        
        //textfields disabled
        txtOrgType.setEnabled(false);
        txtId.setEnabled(false);
        txtUserName.setEnabled(false);
        txtName.setEnabled(false);
        txtPassword.setEnabled(false);
        
        //Setting texts of textfield
        txtUserName.setText(userAccount.getUsername());
        txtName.setText(userAccount.getEmployee().getName());
        txtPassword.setText(userAccount.getPassword());
        
        //Save button disabled
        btnSave.setEnabled(false);
        
        //Update button enabled
        btnUpdate.setEnabled(true); 
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        lblPassword = new javax.swing.JLabel();
        txtOrgType = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        lblOrgType = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblOptions = new javax.swing.JLabel();
        lblDetails = new javax.swing.JLabel();
        lblSave = new javax.swing.JLabel();
        lblUpdate = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 90, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGER UPDATE PANEL");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 3));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 800, -1));

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 90, 30));

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword.setText("Password");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        txtOrgType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrgTypeActionPerformed(evt);
            }
        });
        add(txtOrgType, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 170, -1));

        lblUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserName.setText("UserName");
        add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, 20));

        lblId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblId.setText("Employee ID");
        add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 170, -1));

        lblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Employee Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 170, -1));

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 170, -1));

        lblOrgType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOrgType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrgType.setText("Organization Type");
        add(lblOrgType, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 170, -1));

        btnBack.setText(" Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        lblOptions.setText("Options:");
        lblOptions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 2));
        add(lblOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 750, 30));

        lblDetails.setText("Details:");
        lblDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 2));
        add(lblDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 750, 30));

        lblSave.setText("<- To Save Changes");
        add(lblSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, 30));

        lblUpdate.setText("<- To Update Changes");
        add(lblUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 366, -1, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
           
        //if password pattern check is false, error prompt
        if (passwordPatternCheck()==false)
        {
            

            
            //Show message dialog
            JOptionPane.showMessageDialog(null, "Password should be at least 6 digits and contain at least one upper case letter, one lower case letter, one digit and one special character $, *, # or &.");
            
            return;
        }
        else
        {
            lblPassword.setForeground (Color.BLACK);
            
            txtPassword.setBorder(BorderFactory.createLineBorder(Color.black));
        }
        
        //if username pattern check is false, error prompt
        if (usernamePatternCheck()==false)
        
        {

            
            //Show message dialog
            JOptionPane.showMessageDialog(null, "Username should be in the format of xx_xx@xx.xx");
            
            return;
        } 
        else
        {
            lblUserName.setForeground (Color.BLACK);
            
            txtUserName.setBorder(BorderFactory.createLineBorder(Color.black));
        }
            userAccount.setPassword(txtPassword.getText());
            
            userAccount.setUsername(txtUserName.getText());
            
            userAccount.getEmployee().setName(txtName.getText());
    }//GEN-LAST:event_btnSaveActionPerformed
 
    //check password pattern
    private boolean passwordPatternCheck()
    {
        //Pattern variable that fetches pattern to follow
        Pattern pattern = Pattern.compile("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,}$");
        
        //matcher variable matches pattern with text
        Matcher matcher =pattern.matcher(txtPassword.getText());
        
        //boolean variable fetches result
        boolean bool = matcher.matches();
        
        return bool;
    }
    
    //check username pattern
    private boolean usernamePatternCheck()
    {
        //Pattern variable that fetches pattern to follow
        Pattern pattern = Pattern.compile("^[a-zA-Z0-9]+_[a-zA-Z0-9]+@[a-zA-Z0-9]+.[a-zA-Z0-9]+$");
        
        //matcher variable matches pattern with text
        Matcher matcher = pattern.matcher(txtUserName.getText());
        
        //boolean variable fetches result
        boolean bool = matcher.matches();
        
        return bool;
    }
    

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:.
        
        //Setting textfields
        txtOrgType.setText(organizationName);
        
        //textfield disabled
        txtOrgType.setEnabled(false);
        txtId.setEnabled(false);
        
        //textfield enabled
        txtUserName.setEnabled(true);
        txtName.setEnabled(true);
        txtPassword.setEnabled(true);
        
        //Save button enabled
        btnSave.setEnabled(true);
        
        //Update button disabled
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtOrgTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrgTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrgTypeActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        //current panel layout removed
        sequenceJPanel.remove(this);
        
        //Cardlayout object created
        CardLayout cardLayout = (CardLayout) sequenceJPanel.getLayout();
        
        //previous panel layout loaded
        cardLayout.previous(sequenceJPanel);
        
        customerManagementPanel.populateTable();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDetails;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOptions;
    private javax.swing.JLabel lblOrgType;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSave;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOrgType;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
