/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

//Import Ecosystem
import Business.EcoSystem;

//Import Useraccount
import Business.UserAccount.UserAccount;

//Import cardlayout
import java.awt.CardLayout;

//Import color
import java.awt.Color;

//Import Component
import java.awt.Component;

//Import regex
import java.util.regex.Matcher;
import java.util.regex.Pattern;

//Import borderfactory
import javax.swing.BorderFactory;

//Import JOptionPane
import javax.swing.JOptionPane;

//Import JPanel
import javax.swing.JPanel;

/**
 *
 * @author merwinroy
 */
public class UpdateCustomerJPanel extends javax.swing.JPanel 
{

    /**
     * Creates new form UpdateCustomerJPanel
     */
    
    //JPanel sequenceJPanel object
    JPanel sequenceJPanel;
    
    //UserAccount object
    UserAccount userAccount;
    
    //organizatioName object
    String organizationName;
    
    //ecosystem object
    EcoSystem ecosystem;

    UpdateCustomerJPanel(JPanel sequenceJPanel,UserAccount userAccount,String organaizationName) 
    {
        //initialize components
        initComponents();
        
        
        this.sequenceJPanel = sequenceJPanel;
        
        this.organizationName=organaizationName;
        
        this.userAccount=userAccount;
        
        this.ecosystem=ecosystem;
        
        //textfields disabled
        txtOrgType.setEnabled(false);
        
        txtUserName.setEnabled(false);
        
        txtName.setEnabled(false);
        
        txtPassword.setEnabled(false);
        
        //Setting texts of textfield
        txtOrgType.setText(organizationName);
        
        txtUserName.setText(userAccount.getUsername());
        
        txtName.setText(userAccount.getEmployee().getName());
        
        txtPassword.setText(userAccount.getPassword());
        
        //Save button disabled
        btnSave.setEnabled(false);
        
        //Update button enabled
        btnUpdate.setEnabled(true);
        
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        lblPassword = new javax.swing.JLabel();
        txtOrgType = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblOrgType = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblOptions = new javax.swing.JLabel();
        lblUpdate = new javax.swing.JLabel();
        lblSave = new javax.swing.JLabel();
        lblDetails = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 80, 30));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("CUSTOMER UPDATE PANEL");
        lblTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 3));
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 8, 800, 40));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 80, 30));

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword.setText("Password");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        txtOrgType.setEnabled(false);
        txtOrgType.setPreferredSize(new java.awt.Dimension(200, 22));
        txtOrgType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrgTypeActionPerformed(evt);
            }
        });
        add(txtOrgType, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 170, -1));

        lblUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("UserName");
        add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        txtUserName.setPreferredSize(new java.awt.Dimension(200, 22));
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 170, -1));

        lblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Customer Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        txtName.setPreferredSize(new java.awt.Dimension(200, 22));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 170, -1));

        lblOrgType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOrgType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrgType.setText("Organization Type");
        add(lblOrgType, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        txtPassword.setPreferredSize(new java.awt.Dimension(200, 22));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 170, -1));

        btnBack.setText(" Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        lblOptions.setText("Options:");
        lblOptions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 2));
        add(lblOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 770, 30));

        lblUpdate.setText("<- To Update Changes");
        add(lblUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, 20));

        lblSave.setText("<- To Save Changes");
        add(lblSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, 30));

        lblDetails.setText("Details:");
        lblDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 2));
        add(lblDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 770, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        
        //if password pattern check is false, error prompt
        if (passwordPatternCheck()==false)
        {
 
            
            //Shoe message dialog
            JOptionPane.showMessageDialog(null, "Password should be at least 6 digits and contain at least one upper case letter, one lower case letter, one digit and one special character $, *, # or &.");
            
            return;
        }
        else
        {
            
            lblPassword.setForeground (Color.BLACK);
            
            txtPassword.setBorder(BorderFactory.createLineBorder(Color.black));
            
        }
        
        //if username pattern check is false, error prompt
        if (usernamePatternCheck()==false)
        {
            
            //show message dialog
            
            JOptionPane.showMessageDialog(null, "Username should be in the format of xx_xx@xx.xx");
            
            return;
        } 
        else
        {
            lblUsername.setForeground (Color.BLACK);
            
            txtUserName.setBorder(BorderFactory.createLineBorder(Color.black));
        }
       
        //set username
        userAccount.setUsername(txtUserName.getText());
        
        //set password
        userAccount.setPassword(txtPassword.getText());
        
        //set employee name
        userAccount.getEmployee().setName(txtName.getText());
      
        //show succesful prompt
        JOptionPane.showMessageDialog(null, "Updated successfully");
   
        //textfield disabled
        txtUserName.setEnabled(false);
        
        txtPassword.setEnabled(false);
        
        txtName.setEnabled(false);
        
                
    }//GEN-LAST:event_btnSaveActionPerformed
 
    //check password pattern
    private boolean passwordPatternCheck()
    {
        //Pattern variable that fetches pattern to follow
        Pattern pattern = Pattern.compile("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,}$");
        
        //matcher variable matches pattern with text
        Matcher matcher=pattern.matcher(txtPassword.getText());
        
        //boolean variable fetches result
        boolean bool = matcher.matches();
        
        return bool;
    }
    
    //check username pattern
    private boolean usernamePatternCheck()
    {
        //Pattern variable that fetches pattern to follow
        Pattern pattern=Pattern.compile("^[a-zA-Z0-9]+_[a-zA-Z0-9]+@[a-zA-Z0-9]+.[a-zA-Z0-9]+$");
        
        //matcher variable matches pattern with text
        Matcher matcher=pattern.matcher(txtUserName.getText());
        
        //boolean variable fetches result
        boolean bool = matcher.matches();
        
        return bool;
    }
    
    
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:.
        
        //Setting textfields
        txtOrgType.setText(organizationName);
        
        //textfield disabled
        txtOrgType.setEnabled(false);
        
        //textfield enabled
        txtUserName.setEnabled(true);
        
        txtPassword.setEnabled(true);
        
        txtName.setEnabled(true);
        
        
        //Save button enabled
        btnSave.setEnabled(true);
        
        //update button disabled
        btnUpdate.setEnabled(false);
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtOrgTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrgTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrgTypeActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        //Cardlayout object created
        CardLayout cardLayout = (CardLayout)sequenceJPanel.getLayout();
        
        //current panel layout removed
        sequenceJPanel.remove(this);
        
        //previous panel layout loaded
        cardLayout.previous(sequenceJPanel);
        
        //Components array to fetch and store components from panel
        Component[] components = this.sequenceJPanel.
                getComponents();
        
        //for loop to iterate through components
        for(Component component : components)
        {
            if(component instanceof RestaurantManagementJPanel)
            {
                //RestaurantManagementJPanel object
                RestaurantManagementJPanel resManPanel= (RestaurantManagementJPanel) component;
                
                resManPanel.populateTable(); 
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblDetails;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOptions;
    private javax.swing.JLabel lblOrgType;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSave;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOrgType;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
