

package userinterface.RestaurantAdminRole;

//Import ecosystem
import Business.EcoSystem;

//import organization
import Business.Organization;

//import UserAccount
import Business.UserAccount.UserAccount;

//import company
import Business.Company.Company;


//import CardLayout
import java.awt.CardLayout;

//import JPanel
import javax.swing.JPanel;

//import RestaurantManagementJPanel
import userinterface.SystemAdminWorkArea.RestaurantManagementJPanel;

/**
 *
 * @author merwinroy
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel 
{
    //Jpanel container object
    JPanel container;
    
    //UserAccount object
    UserAccount account;
    
    //Organization object
    Organization organization;
    
    //Company object
    Company company;
    
    //Ecosystem object
    EcoSystem ecoSystem;
    
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel container,UserAccount account, Organization organization, Company company,EcoSystem ecoSystem) 
    {
        //Initialize components
        initComponents();
        
        
        this.container = container;
        
        this.account=account;
        
        this.organization=organization;
        
        this.company = company;
        
        this.ecoSystem = ecoSystem;
        
        //label text is set
        lblValue.setText(company.getName());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnRestaurantManagement = new javax.swing.JButton();
        btnMenuManagement = new javax.swing.JButton();
        btnOrderManagement = new javax.swing.JButton();
        lblRestaurant = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        lblOptions = new javax.swing.JLabel();
        lblOrderManagement = new javax.swing.JLabel();
        lblMenuManagement = new javax.swing.JLabel();
        lblRestaurantManagement = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("ADMIN PANEL");
        lblTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 3));
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 29, 580, 40));

        btnRestaurantManagement.setText("Manage Restaurant ");
        btnRestaurantManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurantManagementActionPerformed(evt);
            }
        });
        add(btnRestaurantManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 180, -1));

        btnMenuManagement.setText("Manage menu");
        btnMenuManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuManagementActionPerformed(evt);
            }
        });
        add(btnMenuManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 180, -1));

        btnOrderManagement.setText("Manage Orders");
        btnOrderManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderManagementActionPerformed(evt);
            }
        });
        add(btnOrderManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 180, -1));

        lblRestaurant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRestaurant.setText("Restaurant :");
        add(lblRestaurant, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 120, 30));
        add(lblValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 130, 30));

        lblOptions.setText("OPTIONS");
        lblOptions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 2));
        add(lblOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 580, 30));

        lblOrderManagement.setText("<- Select option to manage restaurant's orders");
        add(lblOrderManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 196, -1, 30));

        lblMenuManagement.setText("<- Select option to manage restaurant's menu");
        add(lblMenuManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 246, 300, 30));

        lblRestaurantManagement.setText("<- Select option to manage Restaurant ");
        add(lblRestaurantManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 300, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestaurantManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurantManagementActionPerformed
        // TODO add your handling code here:
        
        //Restaurant Jpanel is created
        RestaurantManagementJPanel resManPanel = new RestaurantManagementJPanel(container,ecoSystem);
        
        //panel added to container
        container.add("RestaurantManagementJPanel", resManPanel);
        
        //cardlayout object is created
        CardLayout layout = (CardLayout) container.getLayout();
        
        //next layout is set to container
        layout.next(container);
    }//GEN-LAST:event_btnRestaurantManagementActionPerformed

    private void btnMenuManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuManagementActionPerformed
        
        //MenuManagementJpanel object is created
        MenuManagementJPanel menuManPanel = new MenuManagementJPanel(container,ecoSystem,company,organization,account);
        
        //panel object is added to container
        container.add("MenuManagementJPanel", menuManPanel);
        
        //Cardlayout object is created
        CardLayout layout = (CardLayout) container.getLayout();
        
        //next layout is set to container
        layout.next(container);
    }//GEN-LAST:event_btnMenuManagementActionPerformed

    private void btnOrderManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderManagementActionPerformed
        
        //OrderManagementJPanel object is created
        OrderManagementJPanel orderManPanel = new OrderManagementJPanel(container,ecoSystem,company,organization,account);
        
        //panel object is added to container
        container.add("OrderManagementJPanel", orderManPanel);
        
        //CardLayout object is created
        CardLayout layout = (CardLayout) container.getLayout();
        
        //next layout is set to container
        layout.next(container);
    }//GEN-LAST:event_btnOrderManagementActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuManagement;
    private javax.swing.JButton btnOrderManagement;
    private javax.swing.JButton btnRestaurantManagement;
    private javax.swing.JLabel lblMenuManagement;
    private javax.swing.JLabel lblOptions;
    private javax.swing.JLabel lblOrderManagement;
    private javax.swing.JLabel lblRestaurant;
    private javax.swing.JLabel lblRestaurantManagement;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblValue;
    // End of variables declaration//GEN-END:variables
    
}
