/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

//Import Ecosystem
import Business.EcoSystem;

//Import Organization
import Business.Organization;

//Import UserAccount
import Business.UserAccount.UserAccount;

//Import Order
import Business.Order;

//Import CardLayout
import java.awt.CardLayout;

//Imported ComboBox model
import javax.swing.DefaultComboBoxModel;

//Import JOptionPane
import javax.swing.JOptionPane;

//Import JPanel
import javax.swing.JPanel;

/**
 *
 * @author merwinroy
 */
public class DeliveryAgentAssignmentJPanel extends javax.swing.JPanel 
{
    //JPanel container object created
    private JPanel container;
    
    //Order object created
    Order order;
    
    //Ecosystem object created
    EcoSystem ecoSystem;
    /**
     * Creates new form RequestLabTestJPanel
     * @param container
     * @param order
     * @param ecoSystem
     */
    
    
    public DeliveryAgentAssignmentJPanel(JPanel container, Order order,EcoSystem ecoSystem) 
    {
        //Initialize components
        initComponents();
        
        this.container = container;
        
        this.order = order;
        
        this.ecoSystem=ecoSystem;
        
        
        populateComboBox();
       
    }

   public void  populateComboBox()
   {
       //Combo Box model object is created
        DefaultComboBoxModel comboModel=new DefaultComboBoxModel();
        
        //For loop to iterate through organization directory
        for(Organization org:ecoSystem.getDeliveryManDirectory().getOrganizationDir())
        {
            //for loop to iterate through list of user accounts
            for(UserAccount user:org.getUserAccountDirectory().getUserAccountList())  
            {
                //add user account elements into model
                comboModel.addElement(user); 
            }
        }
        //set model to deliverAgent combobox
       cmbDeliverAgent.setModel(comboModel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * JComboBox<String> seatsComboBox;
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRequest = new javax.swing.JButton();
        lblDeliveryAgent = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        cmbDeliverAgent = new javax.swing.JComboBox<>();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRequest.setText("Request delivery");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });
        add(btnRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        lblDeliveryAgent.setText("Deliver man :");
        add(lblDeliveryAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 130, 30));

        lblEnterprise.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEnterprise.setText("Enterprise :");
        add(lblEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 30));

        cmbDeliverAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDeliverAgentActionPerformed(evt);
            }
        });
        add(cmbDeliverAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 117, 140, 30));

        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("DELIVERY AGENT ASSIGNMENT PANEL");
        lblTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 3));
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 470, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
    
        //Selected Useraccount from table row
        UserAccount selectedUserAccount = (UserAccount) cmbDeliverAgent.getSelectedItem();
        
        if (selectedUserAccount == null)
        {
            JOptionPane.showMessageDialog(null,"Please select a row from table to proceed!");
            return;
        }
        
        //Set Order Status
        order.setOrderStatus("assigned");
        
        //Set Delivery Agent name
        order.setDeliveryPersonName(selectedUserAccount.getEmployee().getName()); 
        
        //Set Delivert Agent username
        order.setDeliveryPersonUser(selectedUserAccount.getUsername()); 
        
        //Set delivery agent id
        order.setDeliveryPersonId(selectedUserAccount.getEmployee().getId()); 
        
        //prompt successful assignment of delivery agent to user
        JOptionPane.showMessageDialog(null, "Delivery man assigned successfully");
        
        return ; 
        
        
    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        //current container removed
        container.remove(this);
        
        //cardlayout object is created
        CardLayout cardLayout = (CardLayout)container.getLayout();
        
        //previous container layout is loaded
        cardLayout.previous(container);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbDeliverAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDeliverAgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDeliverAgentActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequest;
    private javax.swing.JComboBox<String> cmbDeliverAgent;
    private javax.swing.JLabel lblDeliveryAgent;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
