/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.City;
import model.Community;
import model.Encounter;
import model.EncounterHistory;
import model.PatientDirectory;
import model.PersonDirectory;
import model.System1;
import model.VitalSignHistory;

/**
 *
 * @author merwinroy
 */
public class SearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchJPanel
     */
    
    private EncounterHistory eHistory;
    
    private PatientDirectory patientDir;
    
    private VitalSignHistory vHistory;
    
    private Community community;
    
    private City city;
    
    private PersonDirectory personDir;
    
    private System1 systemList;
    
    private JPanel controlPanel;
    
    public SearchJPanel(JPanel controlPanel, System1 systemList, EncounterHistory eHistory, VitalSignHistory vHistory, Community community, PersonDirectory personDir, PatientDirectory patientDir, City city) {
        initComponents();
        this.controlPanel= controlPanel;
        this.systemList = systemList;
        this.eHistory = eHistory;
        this.vHistory = vHistory;
        this.patientDir = patientDir;
        this.personDir = personDir;
        this.community = community;
        this.city = city;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInfo = new javax.swing.JTable();
        lblSearchTitle = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnIDSearch = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("SEARCH PATIENT RECORD");
        lblTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 3));

        tblInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient-ID", "First Name", "Last Name", "Gender", "Age", "Date of Birth", "Phone Number", "House No.", "Street Name", "Community", "City", "Zip", "Blood Pressure", "Temperature", "Pulse", "Check-up Date"
            }
        ));
        jScrollPane1.setViewportView(tblInfo);

        lblSearchTitle.setText("SEARCH BY:");
        lblSearchTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 3));

        lblID.setText("Patient-ID:");

        btnIDSearch.setText("Search");
        btnIDSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDSearchActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(lblSearchTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIDSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSearchTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIDSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIDSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDSearchActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtId.getText());
        
        ArrayList<model.System> idList = systemList.getSystemByID(id);
        
        if(idList.equals(""))
        {
            JOptionPane.showMessageDialog(null,"No data in list");
        }
        else{
                    DefaultTableModel tableModel = (DefaultTableModel) tblInfo.getModel();
        
        //Row count set to 0
        tableModel.setRowCount(0);
        
        for(model.System system:idList){
            Object[] row = new Object[15];
            
            row[0] = system;
            
            row[1] = system.getFirstName();
            row[2] = system.getLastName();
            row[3] = system.getSex();
            row[4] = system.getAge();
            row[5] = system.getDob();
            row[6] = system.getContactNum();
                
            row[7] = system.getHouseNumber();
            row[8] = system.getStreetName();
            row[9] = system.getCommunity();
            row[10] = system.getCity();
            row[11] = system.getZip();
            
            row[12] = system.getBloodPressure();
            row[13] = system.getTemperature();
            row[14] = system.getPulse();
            
            tableModel.addRow(row);
        }
        }
    }//GEN-LAST:event_btnIDSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
                //Current Panel layout removed
        controlPanel.remove(this);
        
        //Previous panel layout is loaded 
        CardLayout cardLayout = (CardLayout) controlPanel.getLayout();
        cardLayout.previous(controlPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnIDSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblSearchTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblInfo;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
                        //Table model is created to display table
        DefaultTableModel tableModel = (DefaultTableModel) tblInfo.getModel();
        
        //Row count set to 0
        tableModel.setRowCount(0);
        
        for(model.System system:systemList.getSystemList()){
            Object[] row = new Object[15];
            
            row[0] = system;
            row[1] = system.getFirstName();
            row[2] = system.getLastName();
            row[3] = system.getSex();
            row[4] = system.getAge();
            row[5] = system.getDob();
            row[6] = system.getContactNum();
                
            row[7] = system.getHouseNumber();
            row[8] = system.getStreetName();
            row[9] = system.getCommunity();
            row[10] = system.getCity();
            row[11] = system.getZip();
            
            row[12] = system.getBloodPressure();
            row[13] = system.getTemperature();
            row[14] = system.getPulse();
            
            tableModel.addRow(row);
        }
    }
}
