/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;
import java.util.HashSet;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.City;
import model.Community;
import model.Encounter;
import model.EncounterHistory;
import model.PatientDirectory;
import model.PersonDirectory;
import model.System1;
import model.VitalSignHistory;

/**
 *
 * @author merwinroy
 */


public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    private EncounterHistory eHistory;
    
    private PatientDirectory patientDir;
    
    private VitalSignHistory vHistory;
    
    private Community community;
    
    private City city;
    
    private PersonDirectory personDir;
    
    private System1 systemList;
    
    private JPanel controlPanel;
    
    public ViewJPanel(JPanel controlPanel,System1 systemList, EncounterHistory eHistory, VitalSignHistory vHistory, Community community, PersonDirectory personDir, PatientDirectory patientDir, City city) {
        initComponents();
        this.controlPanel= controlPanel;
        this.systemList = systemList;
        this.eHistory = eHistory;
        this.vHistory = vHistory;
        this.patientDir = patientDir;
        this.personDir = personDir;
        this.community = community;
        this.city = city;
        
        populateTable();
        
        totalPatients();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewInfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInfo = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        lblOptionInfo = new javax.swing.JLabel();
        btnAbnormal = new javax.swing.JButton();
        lblInfoSearch = new javax.swing.JLabel();
        lblInfoAbnormal = new javax.swing.JLabel();
        lblTotalNo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        lblViewInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewInfo.setText("VIEW PATIENT RECORDS");
        lblViewInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 3));

        tblInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient-ID", "First Name", "Last Name", "Gender", "Age", "Date of Birth", "Phone Number", "House No.", "Street Name", "Community", "City", "Zip", "Blood Pressure", "Temperature", "Pulse", "Check-up Date"
            }
        ));
        jScrollPane1.setViewportView(tblInfo);

        lblTotal.setText("Total Number of Patients:");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblOptionInfo.setText("OPTIONS");
        lblOptionInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 3));

        btnAbnormal.setText("Abnormal Cases");
        btnAbnormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbnormalActionPerformed(evt);
            }
        });

        lblInfoSearch.setText("-> To search through patient records");

        lblInfoAbnormal.setText("-> To find abnormal patient records");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblViewInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
            .addComponent(lblOptionInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblTotal)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotalNo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAbnormal)
                        .addGap(18, 18, 18)
                        .addComponent(lblInfoAbnormal, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSearch)
                        .addGap(80, 80, 80)
                        .addComponent(lblInfoSearch)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblViewInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblOptionInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(lblInfoSearch))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbnormal)
                    .addComponent(lblInfoAbnormal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnRefresh))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        //Removes current panel
        controlPanel.remove(this);
           
        //Loads previous panel
        CardLayout cardLayout = (CardLayout) controlPanel.getLayout();
           
        cardLayout.previous(controlPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        //SearchJPanel object with reference to Jpanel and Fleet object
        SearchJPanel searchPanel = new SearchJPanel(controlPanel,systemList,eHistory,vHistory,community,personDir,patientDir,city);
        
        //SearchJPanel object addedv to controlPanel JPanel object
        controlPanel.add("SearchJPanel", searchPanel);
        
        //SearchJPanel layout loaded into controlPanel
        CardLayout cardLayout = (CardLayout) controlPanel.getLayout();
        
        cardLayout.next(controlPanel);
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnAbnormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbnormalActionPerformed
        // TODO add your handling code here:
        AbnormalJPanel abnormalPanel = new AbnormalJPanel(controlPanel,systemList,eHistory,vHistory,community,personDir,patientDir,city);
        
        //SearchJPanel object addedv to controlPanel JPanel object
        controlPanel.add("AbnormalJPanel", abnormalPanel);
        
        //SearchJPanel layout loaded into controlPanel
        CardLayout cardLayout = (CardLayout) controlPanel.getLayout();
        
        cardLayout.next(controlPanel);
    }//GEN-LAST:event_btnAbnormalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbnormal;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInfoAbnormal;
    private javax.swing.JLabel lblInfoSearch;
    private javax.swing.JLabel lblOptionInfo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalNo;
    private javax.swing.JLabel lblViewInfo;
    private javax.swing.JTable tblInfo;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
                        //Table model is created to display table
        DefaultTableModel tableModel = (DefaultTableModel) tblInfo.getModel();
        
        //Row count set to 0
        tableModel.setRowCount(0);
        
        for(model.System system:systemList.getSystemList()){
            Object[] row = new Object[15];
            
            row[0] = system;
            
            row[1] = system.getFirstName();
            row[2] = system.getLastName();
            row[3] = system.getSex();
            row[4] = system.getAge();
            row[5] = system.getDob();
            row[6] = system.getContactNum();
                
            row[7] = system.getHouseNumber();
            row[8] = system.getStreetName();
            row[9] = system.getCommunity();
            row[10] = system.getCity();
            row[11] = system.getZip();
            
            row[12] = system.getBloodPressure();
            row[13] = system.getTemperature();
            row[14] = system.getPulse();
            
            tableModel.addRow(row);
                 
        }
        
    }

    private void totalPatients() {
        HashSet<Integer> uniqueId = new HashSet<>();
        for(model.System system:systemList.getSystemList())
        {
            uniqueId.add(system.getPatientID());
        }
        int total = uniqueId.size();
        String totalString = (Integer.toString(total));
        lblTotalNo.setText(totalString);
    }
}

